// ============================================================
// LOCAL deploy script — this is the one for `npx hardhat node` /
// `npm run local:start`. It writes config.local.js: a gitignored override
// file app.html always tries to load (harmless 404 anywhere this file
// doesn't exist, e.g. testnet/mainnet deploys), so the real committed
// config.js is never touched. For BOT Chain Testnet, use `npm run deploy`
// (scripts/deploy.js) instead — that one publishes for real and prints a
// scan.bohr.life link; this one never should.
//
// app.html picks which network's contract to actually use by matching the
// *connected wallet's* chain ID against config.NETWORKS at connect time —
// not by which config file happened to load — so this only has to publish
// a NETWORKS.local entry with the right contractAddress; it doesn't need to
// win any "which network is active" decision by itself.
// ============================================================
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

async function main() {
  if (hre.network.name !== "localhost") {
    console.error(
      `\nscripts/deploy-local.js is the LOCAL deploy script — it only runs against --network localhost, ` +
      `not "${hre.network.name}".\n` +
      `For BOT Chain Testnet, run: npm run deploy\n`
    );
    process.exitCode = 1;
    return;
  }

  const [deployer] = await hre.ethers.getSigners();
  const network = await hre.ethers.provider.getNetwork();

  console.log("Deploying to chain", network.chainId.toString(), "as", deployer.address);

  const LegacyVault = await hre.ethers.getContractFactory("LegacyVault");
  const vault = await LegacyVault.deploy();
  await vault.waitForDeployment();
  const address = await vault.getAddress();

  // The genesis-hash check in app.html (verifyGenuineBotChain) doesn't know
  // "local" is safe by default — it compares whatever chain you're on
  // against a known-good genesis hash, the same way it does for
  // testnet/mainnet. A fresh `hardhat node` gets a fresh genesis every
  // time, so fetch the real one now rather than hardcoding a value that
  // would go stale on the next restart.
  const genesisBlock = await hre.ethers.provider.send("eth_getBlockByNumber", ["0x0", false]);

  const chainIdHex = "0x" + network.chainId.toString(16);
  const rpcUrl = hre.network.config.url || "http://127.0.0.1:8545";

  const configLocal = `// AUTO-GENERATED by scripts/deploy-local.js — do not edit, do not commit.
// Re-run the deploy script to regenerate after restarting the local node or
// redeploying — the address and genesis hash below change every time.
//
// app.html always tries to load this file (harmless 404 when it doesn't
// exist, e.g. on a real testnet/mainnet deploy). Loading it only makes a
// "local" entry available in config.NETWORKS for app.html to match against
// — it does NOT by itself make the app use the local contract. That
// happens automatically once a wallet connects: app.html reads the
// wallet's actual chain ID and looks it up in config.NETWORKS, so pointing
// MetaMask at chain 31337 is enough on its own.
(function () {
  var cfg = window.LEGACY_VAULT_CONFIG;
  cfg.NETWORKS.local = {
    id: ${network.chainId},
    chainIdHex: ${JSON.stringify(chainIdHex)},
    caipNetworkId: ${JSON.stringify("eip155:" + network.chainId)},
    name: "Localhost (Hardhat)",
    nativeCurrency: { name: "BOT", symbol: "BOT", decimals: 18 },
    rpcUrls: [${JSON.stringify(rpcUrl)}],
    explorerUrl: "",
    genesisHash: ${JSON.stringify(genesisBlock.hash)},
    contractAddress: ${JSON.stringify(address)}
  };
})();
`;

  fs.writeFileSync(path.join(__dirname, "..", "config.local.js"), configLocal);

  console.log("\n=== DEPLOYED LOCALLY ===");
  console.log("Contract address:", address);
  console.log("Chain ID:", network.chainId.toString());
  console.log("RPC:", rpcUrl);
  console.log("Wrote config.local.js");
  console.log("\nOpen app.html (any URL — no ?network=local needed anymore) and connect");
  console.log("a wallet pointed at chain 31337 / http://127.0.0.1:8545 — the app will");
  console.log("detect it and switch to this contract automatically.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
